# Generated by Django 4.2.2 on 2023-07-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
